"""Mailbox protocol and filesystem bootstrap helpers."""

from houmao.mailbox.errors import MailboxBootstrapError, MailboxError, MailboxProtocolError
from houmao.mailbox.filesystem import (
    FilesystemMailboxPaths,
    MailboxRegistration,
    bootstrap_filesystem_mailbox,
    mailbox_local_sqlite_path,
    load_active_mailbox_registration,
    resolve_active_mailbox_dir,
    read_protocol_version,
    resolve_active_mailbox_inbox_dir,
    resolve_active_mailbox_local_sqlite_path,
    resolve_filesystem_mailbox_paths,
)
from houmao.mailbox.protocol import (
    DEFAULT_NOTIFY_BLOCK_PLACEMENT,
    MAILBOX_PROTOCOL_VERSION,
    MESSAGE_ID_PATTERN,
    NOTIFY_BLOCK_FENCE_INFO_STRING,
    NOTIFY_BLOCK_MAX_CHARS,
    MailboxAttachment,
    MailboxMessage,
    MailboxNotifyAuth,
    MailboxNotifyBlock,
    MailboxPrincipal,
    NotifyBlockPlacement,
    body_has_notify_block_fence,
    extract_notify_block_from_body,
    generate_message_id,
    mailbox_address_path_segment,
    parse_message_document,
    render_notify_block_fence,
    serialize_message_document,
    validate_mailbox_address,
    validate_message_id,
)

__all__ = [
    "DEFAULT_NOTIFY_BLOCK_PLACEMENT",
    "FilesystemMailboxPaths",
    "MAILBOX_PROTOCOL_VERSION",
    "MESSAGE_ID_PATTERN",
    "MailboxAttachment",
    "MailboxBootstrapError",
    "MailboxError",
    "MailboxMessage",
    "MailboxNotifyAuth",
    "MailboxNotifyBlock",
    "MailboxPrincipal",
    "NOTIFY_BLOCK_FENCE_INFO_STRING",
    "NOTIFY_BLOCK_MAX_CHARS",
    "NotifyBlockPlacement",
    "MailboxRegistration",
    "MailboxProtocolError",
    "body_has_notify_block_fence",
    "bootstrap_filesystem_mailbox",
    "extract_notify_block_from_body",
    "generate_message_id",
    "load_active_mailbox_registration",
    "mailbox_local_sqlite_path",
    "mailbox_address_path_segment",
    "parse_message_document",
    "read_protocol_version",
    "render_notify_block_fence",
    "resolve_active_mailbox_dir",
    "resolve_active_mailbox_inbox_dir",
    "resolve_active_mailbox_local_sqlite_path",
    "resolve_filesystem_mailbox_paths",
    "serialize_message_document",
    "validate_mailbox_address",
    "validate_message_id",
]
