"""Command-template declarations for this command family."""

from __future__ import annotations

from ..builders import (
    _choice,
    _clear,
    _conflict,
    _f,
    _flag,
    _int,
    _many,
    _path,
    _req,
    _template,
)
from ..models import (
    CommandTemplate,
    _PROMPT_MODE_CHOICES,
    _RELAUNCH_CHAT_SESSION_MODES,
)


def templates() -> list[CommandTemplate]:
    """Return first-class project command templates."""

    prompt_mode = _choice(
        "prompt_mode",
        "--prompt-mode",
        "Persist an explicit operator prompt mode.",
        _PROMPT_MODE_CHOICES,
        default_action="omit-to-inherit",
    )
    common_profile_fields = (
        _f("agent_name", "--agent-name", "Default managed-agent name."),
        _f("agent_id", "--agent-id", "Default managed-agent id."),
        _f("workdir", "--workdir", "Default runtime workdir."),
        _f("auth", "--auth", "Default credential/auth override."),
        _f("model", "--model", "Launch-owned model override."),
        _int("reasoning_level", "--reasoning-level", "Launch-owned reasoning preset index."),
        prompt_mode,
        _many("env_set", "--env-set", "Persistent launch environment record."),
        _many("system_skill_set", "--system-skill-set", "Packaged system-skill set."),
        _many("system_skill", "--system-skill", "Packaged system skill."),
        _choice(
            "system_skills_mode",
            "--system-skills-mode",
            "Managed system-skill policy mode.",
            ("inherit", "extend", "replace", "none"),
        ),
        _flag("no_system_skills", "--no-system-skills", "Disable managed system skills."),
        _flag("clear_system_skills", "--clear-system-skills", "Clear system-skill policy."),
        _many("add_registered_skill", "--add-registered-skill", "Add project skill override."),
        _many(
            "remove_registered_skill",
            "--remove-registered-skill",
            "Remove project skill override.",
        ),
        _many("add_private_skill", "--add-private-skill", "Copy profile-private skill."),
        _many(
            "add_private_skill_symlink",
            "--add-private-skill-symlink",
            "Symlink profile-private skill.",
        ),
        _many("remove_private_skill", "--remove-private-skill", "Remove private skill source."),
        _choice(
            "mail_transport",
            "--mail-transport",
            "Declarative mailbox transport.",
            ("filesystem", "stalwart"),
        ),
        _f("mail_principal_id", "--mail-principal-id", "Declarative mailbox principal id."),
        _f("mail_address", "--mail-address", "Declarative mailbox address."),
        _f("mail_root", "--mail-root", "Declarative filesystem mailbox root."),
        _f("mail_base_url", "--mail-base-url", "Declarative Stalwart base URL."),
        _f("mail_jmap_url", "--mail-jmap-url", "Declarative Stalwart JMAP URL."),
        _f("mail_management_url", "--mail-management-url", "Declarative Stalwart management URL."),
        _flag(
            "headless",
            "--headless",
            "Persist headless launch posture.",
            default_action="omit-to-inherit",
        ),
        _flag("no_gateway", "--no-gateway", "Disable gateway auto-attach."),
        _flag(
            "managed_header",
            "--managed-header",
            "Persist managed-header enabled/disabled posture.",
            default_action="omit-to-inherit",
            negative_option="--no-managed-header",
        ),
        _many(
            "managed_header_section", "--managed-header-section", "Managed-header section policy."
        ),
        _int("gateway_port", "--gateway-port", "Fixed loopback gateway port."),
        _choice(
            "relaunch_chat_session_mode",
            "--relaunch-chat-session-mode",
            "Relaunch chat-session mode.",
            _RELAUNCH_CHAT_SESSION_MODES,
        ),
        _f("relaunch_chat_session_id", "--relaunch-chat-session-id", "Relaunch chat-session id."),
        _choice(
            "prompt_overlay_mode",
            "--prompt-overlay-mode",
            "Prompt overlay mode.",
            ("append", "replace"),
        ),
        _f("prompt_overlay_text", "--prompt-overlay-text", "Inline prompt overlay."),
        _path("prompt_overlay_file", "--prompt-overlay-file", "Prompt overlay file."),
        _f(
            "gateway_mail_notifier_appendix_text",
            "--gateway-mail-notifier-appendix-text",
            "Mail-notifier prompt appendix.",
        ),
        _f("memo_seed_text", "--memo-seed-text", "Inline memo seed."),
        _path("memo_seed_file", "--memo-seed-file", "Memo seed file."),
        _path("memo_seed_dir", "--memo-seed-dir", "Memo seed directory."),
    )
    profile_conflicts = (
        _conflict(
            "prompt_mode",
            "clear_prompt_mode",
            message="Prompt mode cannot be set and cleared in the same command.",
        ),
        _conflict(
            "headless",
            "clear_headless",
            message="Launch posture cannot be set and cleared in the same command.",
        ),
        _conflict(
            "managed_header",
            "clear_managed_header",
            message="Managed header cannot be set and cleared in the same command.",
        ),
        _conflict(
            "prompt_overlay_text",
            "prompt_overlay_file",
            "clear_prompt_overlay",
            message="Prompt overlay text, file, and clear are mutually exclusive.",
        ),
        _conflict(
            "memo_seed_text",
            "memo_seed_file",
            "memo_seed_dir",
            "clear_memo_seed",
            message="Memo seed text, file, directory, and clear are mutually exclusive.",
        ),
    )
    profile_clear_fields = (
        _clear("clear_agent_name", "--clear-agent-name", "agent_name"),
        _clear("clear_agent_id", "--clear-agent-id", "agent_id"),
        _clear("clear_workdir", "--clear-workdir", "workdir"),
        _clear("clear_auth", "--clear-auth", "auth"),
        _clear("clear_model", "--clear-model", "model"),
        _clear("clear_reasoning_level", "--clear-reasoning-level", "reasoning_level"),
        _clear("clear_prompt_mode", "--clear-prompt-mode", "prompt_mode"),
        _clear("clear_env", "--clear-env", "env_set"),
        _clear("clear_mailbox", "--clear-mailbox", "mailbox"),
        _clear("clear_headless", "--clear-headless", "headless"),
        _clear("clear_managed_header", "--clear-managed-header", "managed_header"),
        _many(
            "clear_managed_header_section",
            "--clear-managed-header-section",
            "Clear one managed-header section.",
        ),
        _clear(
            "clear_managed_header_sections",
            "--clear-managed-header-sections",
            "managed_header_section",
        ),
        _clear(
            "clear_relaunch_chat_session",
            "--clear-relaunch-chat-session",
            "relaunch_chat_session",
        ),
        _clear("clear_prompt_overlay", "--clear-prompt-overlay", "prompt_overlay"),
        _clear(
            "clear_gateway_mail_notifier_appendix",
            "--clear-gateway-mail-notifier-appendix",
            "gateway_mail_notifier_appendix_text",
        ),
        _clear("clear_memo_seed", "--clear-memo-seed", "memo_seed"),
    )
    specialist_create_fields = (
        _req("name", "--name", "Specialist name."),
        _req("tool", "--tool", "Tool lane."),
        _f("system_prompt", "--system-prompt", "Inline system prompt."),
        _path("system_prompt_file", "--system-prompt-file", "System prompt file."),
        _f("setup", "--setup", "Tool setup name."),
        _f("credential", "--credential", "Credential bundle name."),
        _f("api_key", "--api-key", "Common API key input."),
        _f("base_url", "--base-url", "Common base URL input."),
        _f("claude_auth_token", "--claude-auth-token", "Claude auth token."),
        _f("claude_oauth_token", "--claude-oauth-token", "Claude OAuth token."),
        _f("model", "--model", "Launch-owned model name."),
        _int("reasoning_level", "--reasoning-level", "Launch-owned reasoning preset index."),
        _f("claude_model", "--claude-model", "Claude model compatibility alias."),
        _path(
            "claude_state_template_file", "--claude-state-template-file", "Claude state template."
        ),
        _path("claude_config_dir", "--claude-config-dir", "Claude config dir import."),
        _f("codex_org_id", "--codex-org-id", "Codex organization id."),
        _path("codex_auth_json", "--codex-auth-json", "Codex auth.json file."),
        _f("google_api_key", "--google-api-key", "Gemini Google API key."),
        _flag("use_vertex_ai", "--use-vertex-ai", "Use Gemini Vertex AI mode."),
        _path("gemini_oauth_creds", "--gemini-oauth-creds", "Gemini OAuth credentials."),
        _many("skill", "--skill", "Registered project skill."),
        _many("with_skill", "--with-skill", "Skill directory to register and bind."),
        _many("env_set", "--env-set", "Persistent specialist env record."),
        _many("system_skill_set", "--system-skill-set", "Packaged system-skill set."),
        _many("system_skill", "--system-skill", "Packaged system skill."),
        _choice(
            "system_skills_mode",
            "--system-skills-mode",
            "Specialist system-skill policy mode.",
            ("default", "extend", "replace", "none"),
        ),
        _flag("no_system_skills", "--no-system-skills", "Disable managed system skills."),
        _flag("clear_system_skills", "--clear-system-skills", "Clear system-skill policy."),
        _flag("no_unattended", "--no-unattended", "Persist as_is prompt mode."),
        _flag("yes", "--yes", "Confirm replacement."),
    )
    specialist_set_fields = (
        _req("name", "--name", "Specialist name."),
        _f("system_prompt", "--system-prompt", "Replacement system prompt."),
        _path("system_prompt_file", "--system-prompt-file", "Replacement system prompt file."),
        _clear("clear_system_prompt", "--clear-system-prompt", "system_prompt"),
        _f("setup", "--setup", "Setup override."),
        _f("credential", "--credential", "Credential override."),
        prompt_mode,
        _clear("clear_prompt_mode", "--clear-prompt-mode", "prompt_mode"),
        _f("model", "--model", "Launch-owned model override."),
        _clear("clear_model", "--clear-model", "model"),
        _int("reasoning_level", "--reasoning-level", "Launch-owned reasoning preset index."),
        _clear("clear_reasoning_level", "--clear-reasoning-level", "reasoning_level"),
        _many("env_set", "--env-set", "Persistent specialist env replacement."),
        _clear("clear_env", "--clear-env", "env_set"),
        _many("system_skill_set", "--system-skill-set", "Packaged system-skill set."),
        _many("system_skill", "--system-skill", "Packaged system skill."),
        _choice(
            "system_skills_mode",
            "--system-skills-mode",
            "Specialist system-skill policy mode.",
            ("default", "extend", "replace", "none"),
        ),
        _flag("no_system_skills", "--no-system-skills", "Disable managed system skills."),
        _flag("clear_system_skills", "--clear-system-skills", "Clear system-skill policy."),
        _many("with_skill", "--with-skill", "Skill directory to register and bind."),
        _many("add_skill", "--add-skill", "Add registered skill."),
        _many("remove_skill", "--remove-skill", "Remove registered skill."),
        _flag("clear_skills", "--clear-skills", "Clear registered skills."),
    )
    return [
        _template(
            "project.specialist.create",
            ("project", "specialist", "create"),
            "Create one project-local specialist.",
            specialist_create_fields,
            family="project.specialist",
            conflicts=(
                _conflict(
                    "system_prompt",
                    "system_prompt_file",
                    message="System prompt text and file are mutually exclusive.",
                ),
                _conflict(
                    "model", "claude_model", message="Model and Claude model alias conflict."
                ),
            ),
        ),
        _template(
            "project.specialist.set",
            ("project", "specialist", "set"),
            "Patch one project-local specialist.",
            specialist_set_fields,
            family="project.specialist",
            conflicts=(
                _conflict(
                    "system_prompt",
                    "system_prompt_file",
                    "clear_system_prompt",
                    message="System prompt set and clear fields are mutually exclusive.",
                ),
                _conflict(
                    "prompt_mode",
                    "clear_prompt_mode",
                    message="Prompt mode cannot be set and cleared in the same command.",
                ),
                _conflict(
                    "model",
                    "clear_model",
                    message="Model cannot be set and cleared in the same command.",
                ),
                _conflict(
                    "reasoning_level",
                    "clear_reasoning_level",
                    message="Reasoning level cannot be set and cleared in the same command.",
                ),
                _conflict("env_set", "clear_env", message="Env records cannot be set and cleared."),
            ),
        ),
        _template(
            "project.profile.create",
            ("project", "profile", "create"),
            "Create one specialist-backed project profile.",
            (
                _req("name", "--name", "Project profile name."),
                _req("specialist", "--specialist", "Source specialist."),
                *common_profile_fields,
                _flag("yes", "--yes", "Confirm replacement."),
            ),
            family="project.profile",
            conflicts=profile_conflicts,
        ),
        _template(
            "project.profile.set",
            ("project", "profile", "set"),
            "Patch one specialist-backed project profile.",
            (
                _req("name", "--name", "Project profile name."),
                *common_profile_fields,
                *profile_clear_fields,
            ),
            family="project.profile",
            conflicts=profile_conflicts,
        ),
        _template(
            "project.agents.launch",
            ("project", "agents", "launch"),
            "Launch one project managed agent from a specialist or profile.",
            (
                _f("specialist", "--specialist", "Source specialist."),
                _f("profile", "--profile", "Source project profile."),
                _f("name", "--name", "Managed-agent instance name."),
                _f("auth", "--auth", "One-shot auth override."),
                _f("model", "--model", "One-shot model override."),
                _int("reasoning_level", "--reasoning-level", "One-shot reasoning preset index."),
                _f("session_name", "--session-name", "tmux session name."),
                _flag(
                    "headless",
                    "--headless",
                    "Request headless launch posture.",
                    default_action="omit-to-inherit",
                    negative_option="--no-headless",
                ),
                _flag("no_gateway", "--no-gateway", "Disable gateway auto-attach."),
                _int("gateway_port", "--gateway-port", "Gateway port."),
                _flag("gateway_background", "--gateway-background", "Run gateway in background."),
                _f("workdir", "--workdir", "Runtime workdir."),
                _many("env_set", "--env-set", "One-shot runtime env override."),
                _choice(
                    "mail_transport",
                    "--mail-transport",
                    "Runtime mailbox transport.",
                    ("filesystem", "email"),
                ),
                _f("mail_root", "--mail-root", "Filesystem mailbox root."),
                _f("mail_account_dir", "--mail-account-dir", "Filesystem mailbox account dir."),
                _flag(
                    "managed_header",
                    "--managed-header",
                    "One-shot managed-header posture.",
                    negative_option="--no-managed-header",
                    default_action="omit-to-inherit",
                ),
                _many(
                    "managed_header_section",
                    "--managed-header-section",
                    "Managed-header section override.",
                ),
                _flag("reuse_home", "--reuse-home", "Reuse compatible stopped home."),
                _choice("force", "--force", "Managed launch force mode.", ("reuse", "clean")),
            ),
            family="project.agents",
            required_one_of=(("specialist", "profile"),),
            conflicts=(
                _conflict(
                    "specialist",
                    "profile",
                    message="Specialist and profile sources are mutually exclusive.",
                ),
                _conflict(
                    "no_gateway",
                    "gateway_port",
                    message="Gateway cannot be disabled and assigned a port.",
                ),
                _conflict(
                    "no_gateway",
                    "gateway_background",
                    message="Gateway cannot be disabled and backgrounded.",
                ),
            ),
        ),
    ]
